export const products = [
  {
    id: 1,
    name: 'Худи с принтом',
    price: 999,
    category: 'hoodie',
    image: ' images/hoodie1.jpg',
  },
  {
    id: 2,
    name: 'Черное худи',
    price: 1299,
    category: 'hoodie',
    image: ' images/hoodie2.jpeg',
  },
  {
    id: 3,
    name: 'Серое худи',
    price: 1099,
    category: 'hoodie',
    image: ' images/hoodie3.jpg',
  },
  {
    id: 4,
    name: 'Худи Oversize',
    price: 1499,
    category: 'hoodie',
    image: ' images/hoodie2.jpeg',
  },
  {
    id: 5,
    name: 'Худи с капюшоном',
    price: 1199,
    category: 'hoodie',
    image: ' images/hoodie2.jpeg',
  },
  {
    id: 6,
    name: 'Худи унисекс',
    price: 1399,
    category: 'hoodie',
    image: ' images/hoodie2.jpeg',
  },
  {
    id: 7,
    name: 'Шорты спортивные',
    price: 799,
    category: 'shorts',
    image: ' images/shorts.jpg',
  },
  {
    id: 8,
    name: 'Шорты джинсовые',
    price: 1599,
    category: 'shorts',
    image: ' images/shorts.jpg',
  },
  {
    id: 9,
    name: 'Шорты беговые',
    price: 899,
    category: 'shorts',
    image: ' images/shorts.jpg',
  },
  {
    id: 10,
    name: 'Шорты пляжные',
    price: 699,
    category: 'shorts',
    image: ' images/shorts.jpg',
  },
  {
    id: 11,
    name: 'Шорты с карманами',
    price: 999,
    category: 'shorts',
    image: ' images/shorts.jpg',
  },
  {
    id: 12,
    name: 'Шорты хлопковые',
    price: 849,
    category: 'shorts',
    image: ' images/shorts.jpg',
  },
];